#!/usr/bin/env python3
"""Embed the crt-royale-xm29plus textures as committed RGBA8 C arrays.

The pipeline samples two textures (the NEC XM29 color LUT and the large slot-mask
LUT). Like the SPIR-V headers, we commit them as C arrays so parallel-rdp stays
self-contained (no runtime PNG decode, no asset path lookups). The source PNGs are
8-bit RGB; Vulkan rarely supports plain RGB8, so we expand to RGBA8 (alpha 255).
The data is treated as LINEAR (the masks are already linear; uploaded as UNORM).

Run from this directory after changing a source PNG:
    python embed_textures.py

Regenerates ../../parallel-rdp/crt_royale_textures.hpp. Symbol names and the
expected dimensions are fixed by parallel-rdp/crt_royale_contract.md.

Stream C.0.
"""

import os

from PIL import Image

# (symbol_prefix, png_filename, expected_width, expected_height)
TEXTURES = [
    ("royale_color_lut", "nec_xm29plus_capture.png", 1024, 32),
    ("royale_slot_mask_large", "slot_mask_large.png", 512, 512),
]

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(
    os.path.join(HERE, "..", "..", "..", "parallel-rdp", "crt_royale_textures.hpp")
)


def emit_texture(prefix, png_name, want_w, want_h):
    path = os.path.join(HERE, png_name)
    image = Image.open(path).convert("RGBA")  # expands RGB -> RGBA8, alpha = 255
    width, height = image.size
    # Validate against the contract so a swapped/re-exported PNG fails loudly.
    assert (width, height) == (want_w, want_h), (
        f"{png_name}: expected {want_w}x{want_h}, got {width}x{height}"
    )
    data = image.tobytes()  # row-major, tightly packed RGBA8
    assert len(data) == width * height * 4

    # Group into fixed-count rows joined by commas; never split inside a number.
    values = [str(b) for b in data]
    per_row = 24
    rows = [",".join(values[i:i + per_row]) for i in range(0, len(values), per_row)]
    array = ",\n    ".join(rows)
    return (
        f"static const uint32_t {prefix}_width = {width};\n"
        f"static const uint32_t {prefix}_height = {height};\n"
        f"static const uint8_t {prefix}_data[{len(data)}] = {{\n"
        f"    {array}\n"
        f"}};\n"
    )


def main():
    blocks = [emit_texture(*t) for t in TEXTURES]
    header = (
        "// GENERATED by data/shader/crt-royale/embed_textures.py -- do not edit.\n"
        "// crt-royale-xm29plus textures as RGBA8 (linear). See crt_royale_contract.md.\n"
        "\n"
        "#ifndef CRT_ROYALE_TEXTURES_HPP\n"
        "#define CRT_ROYALE_TEXTURES_HPP\n"
        "\n"
        "#include <cstdint>\n"
        "\n"
        + "\n".join(blocks)
        + "\n#endif  // CRT_ROYALE_TEXTURES_HPP\n"
    )
    with open(OUT, "w", newline="\n") as f:
        f.write(header)
    print(f"wrote {OUT} ({sum(len(b) for b in blocks)} bytes of C source)")


if __name__ == "__main__":
    main()
