#!/bin/bash
#
# Compile the crt-royale-xm29plus pass shaders to SPIR-V and assemble them into
# parallel-rdp/spirv_crt_royale.hpp as committed C arrays (see
# parallel-rdp/crt_royale_contract.md for the symbol-naming contract).
#
# Mirrors data/shader/output.sh: glslc emits a `{0x..,..}` initializer with
# -mfmt=c, which we wrap as `static const uint32_t NAME[] = {...};`. No glslc runs
# at build time; this is an offline regeneration step.
#
# Usage (glslc must be reachable, or pass its path):
#   GLSLC=/path/to/glslc.exe ./output.sh
#
# Stream B.0 (build scaffold) / B.Z (header generation).

set -euo pipefail

GLSLC="${GLSLC:-glslc}"
HERE="$(cd "$(dirname "$0")" && pwd)"
OUT="$HERE/../../../parallel-rdp/spirv_crt_royale.hpp"

# Pass list: "<NN> <name>" in execution order. Each entry compiles
# <NN>_<name>.vert and <NN>_<name>.frag. Passes are appended here as they are
# translated; idx 10 (geometry) is the final pass drawn to the swapchain.
PASSES=(
    "00 lut"
    "01 linearize"
)

emit_stage() {  # $1 = array symbol, $2 = source path
    local name="$1" src="$2" tmp
    tmp="$(mktemp)"
    "$GLSLC" -O --target-env=vulkan1.1 -mfmt=c "$src" -o "$tmp"
    printf 'static const uint32_t %s[] =\n' "$name"
    cat "$tmp"
    printf ';\n\n'
    rm -f "$tmp"
}

{
    echo "// GENERATED by data/shader/crt-royale/output.sh -- do not edit."
    echo "#pragma once"
    echo
    for entry in "${PASSES[@]}"; do
        # shellcheck disable=SC2086
        set -- $entry
        idx="$1"
        name="$2"
        emit_stage "royale_${idx}_${name}_vert_spirv" "$HERE/${idx}_${name}.vert"
        emit_stage "royale_${idx}_${name}_frag_spirv" "$HERE/${idx}_${name}.frag"
    done
} >"$OUT"

echo "wrote $OUT"
